### ISSUE TITLE
Xml mal formado al enviar evento del receptor: Notificación de Recepción

### ISSUE THREAD

**Issue by hriveros22** [roshkadev/rshk-jsifenlib#11]
Al intentar enviar el evento de notificación de recepción del receptor, el ws de la SET devuelve la respuesta bruta: 
<?xml version="1.0" encoding="UTF-8"?>
<env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope"><env:Header/><env:Body><ns2:rRetEnviDe xmlns:ns2="http://ekuatia.set.gov.py/sifen/xsd"><ns2:rProtDe><ns2:dFecProc>2022-06-27T10:36:39-04:00</ns2:dFecProc><ns2:dEstRes>Rechazado</ns2:dEstRes><ns2:gResProc><ns2:dCodRes>0160</ns2:dCodRes><ns2:dMsgRes>XML Mal Formado.</ns2:dMsgRes></ns2:gResProc></ns2:rProtDe></ns2:rRetEnviDe></env:Body></env:Envelope>

En el server log: 
10:36:39,929 WARNING [class com.roshka.sifen.internal.request.ReqRecEventoDe] (default task-1) El nombre del nodo [rRetEnviDe] no coincide con el nombre esperado [rRetEnviEventoDe]

Por lo que puedo notar, en el xml debe formarse el tag con el nombre: rRetEnviEventoDe, pero se está formando con el nombre: rRetEnviDe

Para los demas eventos del receptor no tuve inconvenientes y pude enviarlos sin problemas.

Estoy usando la ultima versión de la api: rshk-jsifenlib 0.2.1

Comparto el cdc de la FE que estoy utilizando: 01800034686001001000004322022062417878047569

**Comment by martinzarza** [comment]
@hriveros22 Podrías compartir el código que estás utilizando para el evento con el que tenés el error?

**Comment by martinzarza** [comment]
Verifico que no se está seteando un valor al campo obligatorio `dTotalGs` en el evento `notifRecep`. Podrías agregar ese valor y probar de vuelta? Ya que el resto de cosas están en orden.

![image](https://user-images.githubusercontent.com/54747048/176023932-ca0f63d1-0222-4cec-9bc5-c490110d496d.png)

**Comment by hriveros22** [comment]
efectivamente, era por el campo dTotalGs, solucionado!
