### ISSUE TITLE
Envio en lote de los DE a la SET - numero de lote faltante en RespuestaRecepcionLoteDE

### ISSUE THREAD

**Issue by hriveros22** [roshkadev/rshk-jsifenlib#12]
Buenos dias, en el envio en lote de los DE a la SET, veo que en la clase RespuestaRecepcionLoteDE estaria faltando el atributo: dProtConsLote

Ya que en caso de que el lote fuese transmitido correctamente, la SET genera un numero de lote para luego poder utilizar en la consulta: siResultLoteDE, de tal manera a monitorear luego de la transmisión del lote, si dicho lote fue procesado con exito por la SET.

**Comment by martinzarza** [comment]
Veo que el atributo `dProtConsLote` está presente en la clase `RespuestaRecepcionLoteDE`.
O te referís a que en la respuesta no se está seteando el valor?

**Comment by hriveros22** [comment]
Error mio Martin, cierro el issue, estaré luego probando en la respuesta el seteo del mismo!
