### ISSUE TITLE
Ruc invalido

### ISSUE THREAD

**Issue by rafaelviny** [roshkadev/rshk-jsifenlib#15]
En la clase `TgEmis`, metodo `setdRucEm` adiciona 0 a la izquierda. Al enviar la requisicion me devuelve 
	`<ns2:dMsgRes>XML malformado [El valor 02534435 del elemento: dRucEm es invalido]</ns2:dMsgRes>`

si dejo el `setdRucEm `sin el` SifenUtil.leftPad` me devuelve 
`	<ns2:dMsgRes>RUC del emisor no est&#225; habilitado para utilizar este tipo de servicio</ns2:dMsgRes>`

parece que ni todos los RUC iran adicionado zero al inicio.

**Comment by martinzarza** [comment]
Estoy de acuerdo, creo que no todos los RUCs deben tener 0 al principio. Vamos a mirar más en detalle este inconveniente.

Gracias por el comentario @rafaelviny.

**Comment by rafaelviny** [comment]
@martinzarza  recordando que en la hora de generar el CDC si debe completar los 8 campos con ZERO como está haciendo en el set  `setdRucEm `

**Comment by martinzarza** [comment]
_Bug_ arreglado en la [versión 0.2.2](https://github.com/roshkadev/rshk-jsifenlib/releases/tag/v0.2.2).
