### ISSUE TITLE
Ver xml enviado y recibido

### ISSUE THREAD

**Issue by desarrollo02** [roshkadev/rshk-jsifenlib#20]
¿Cómo puedo obtener el XML enviado y el XML de respuesta?

**Comment by martinzarza** [comment]
@desarrollo02 El XML enviado no es posible obtener en este momento. Sí podes generar el XML de tu Documento Electrónico:

```java
DocumentoElectronico DE = new DocumentoElectronico();
String xml = DE.generarXml();
```

Y también podés ver la respuesta enviada desde Sifen:
```java
RespuestaConsultaRUC response = Sifen.consultaRUC("ruc");
ret.getRespuestaBruta();
```

**Comment by pablo** [comment]
Gracias Martín!
