### ISSUE TITLE
Consultar estado CDC

### ISSUE THREAD

**Issue by josecolman** [roshkadev/rshk-jsifenlib#21]
Como se podria consultar el estado de un CDC ya sea en lote o en forma individual?

**Comment by franbar95** [comment]
[https://github.com/roshkadev/rshk-jsifenlib/blob/master/src/test/java/com/roshka/sifen/test/soap/SOAPTests.java](url)

`  public void testConsultaDE() throws SifenException {
        RespuestaConsultaDE ret = Sifen.consultaDE("01800805534001002000000722021040613265708133");
        logger.info(ret.toString());
    }`

`    public void testConsultaLoteDe() throws SifenException {
        RespuestaConsultaLoteDE ret = Sifen.consultaLoteDE("109051592123784");
        logger.info(ret.toString());
    }`
