### ISSUE TITLE
Constantes URL xsi:schemaLocation definidas erróneamente

### ISSUE THREAD

**Issue by dschulz** [roshkadev/rshk-jsifenlib#22]
Aparentemente las URLs que definen la URL del XSD para xsi:schemaLocation se concatenan incorrectamente en las líneas 15 y 16. El URL final contiene un espacio y es inválido.

https://github.com/roshkadev/rshk-jsifenlib/blob/93fab61f9c0dfffc85e25afbebdd5bccea00a2d9/src/main/java/com/roshka/sifen/internal/Constants.java#L15

https://github.com/roshkadev/rshk-jsifenlib/blob/93fab61f9c0dfffc85e25afbebdd5bccea00a2d9/src/main/java/com/roshka/sifen/internal/Constants.java#L16

Actualmente:

![image](https://user-images.githubusercontent.com/36960/213707414-0692fefd-e960-47e0-b22b-c37bc5925c2d.png)

URL correcta:
![image](https://user-images.githubusercontent.com/36960/213707612-2c6cac62-0dc8-4522-a4ea-680af6b6f7fe.png)

Si hay una buena razón por la que las constantes fueron definidas de esta manera, favor ignorar y cerrar rabiosamente el ticket.

**Comment by martinzarza** [comment]
@dschulz No recuerdo exactamente, pero creo que se hizo de esa forma por un motivo. Tampoco tuvimos problemas por eso, así que por ahora dejaría así.

**Comment by pablo** [comment]
Voy a hacer pruebas con esto y, si corresponde, hacemos el MERGE.

**Comment by dschulz** [comment]
Entendido, gracias por la aclaración @ysidromdenis. Cierro el issue ya que es irrelevante.
