### ISSUE TITLE
Como volver a utilizar el cdc

### ISSUE THREAD

**Issue by desarrollo02** [roshkadev/rshk-jsifenlib#24]
Buenas.

¿Como se puede volver a reutilizar un cdc?, seria el caso, en que los datos correspondientes a cdc no cambian, no veo una forma de asignar el cdc a la clase DocumentoElectronico

**Comment by martinzarza** [comment]
El CDC siempre se genera de forma automática. Para generar uno previamente utilizado tenés que setear el mismo Código de Seguridad que se usó en el anterior.

`TgOpeDE.setdCodSeg()`

Con este código, y si el resto de datos de la factura no cambió, el CDC generado debería ser igual al anterior.
