### ISSUE TITLE
Envio de lote

### ISSUE THREAD

**Issue by desarrollo02** [roshkadev/rshk-jsifenlib#25]
Buenas.

Al realizar el envió de lote utilizando el siguiente método:

RespuestaRecepcionLoteDE respuesta = Sifen.recepcionLoteDE(deList);

Recibo la siguiente respuesta:

<?xml version="1.0" encoding="UTF-8"?>
<env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope"><env:Header/>
    <env:Body>
         <ns2:rResEnviLoteDe xmlns:ns2="http://ekuatia.set.gov.py/sifen/xsd"><ns2:dFecProc>2023-02-16T10:05:12-03:00</ns2:dFecProc>
<ns2:dCodRes>0301</ns2:dCodRes><ns2:dMsgRes>Lote no encolado para procesamiento</ns2:dMsgRes><ns2:dTpoProces>0</ns2:dTpoProces></ns2:rResEnviLoteDe>
</env:Body>
</env:Envelope>

¿Es correcta la forma en que estoy enviando?

Veo que el problema es el RUC del emisor que solo tiene 7 digitos, como se haria el envio para este tipo de RUC?

**Comment by pablo** [comment]
Esto se puede dar por dos motivos:

1) La SET está con problemas (este suele ser el caso más frecuente)
2) La SET ya sabe que te va a rechazar toditos los docs del lote con su pre-validación ya, entonces ni te acepta el lote y no te da un mensaje

Otro tema importante es que, por ahora, la SET solo soporta el envío de lotes asíncronos en Producción.
