### ISSUE TITLE
ERROR:  'Las comillas de apertura se deben utilizar para el atributo "classId" asociado a un tipo de elemento "object".'

### ISSUE THREAD

**Issue by mcespedeso** [roshkadev/rshk-jsifenlib#26]
Hola !

Cuando envio mi Documento Electronico, tengo este error.

*
mar 05, 2023 9:00:51 PM com.roshka.sifen.Sifen setSifenConfig
INFORMACIÓN: Configuración de Sifen guardada correctamente
mar 05, 2023 9:00:51 PM com.roshka.sifen.Sifen recepcionDE
INFORMACIÓN: Preparando petición 'Recepción de DE'
mar 05, 2023 9:00:52 PM com.roshka.sifen.internal.request.BaseRequest makeRequest
INFORMACIÓN: XML generado, se realiza la petición
mar 05, 2023 9:00:52 PM com.roshka.sifen.internal.helpers.SSLContextHelper getContextFromConfig
INFORMACIÓN: Contexto SSL no cargado aún. Empezando carga...
mar 05, 2023 9:00:52 PM com.roshka.sifen.internal.helpers.SoapHelper makeSoapRequest
INFORMACIÓN: Conectando a: https://sifen-test.set.gov.py/de/ws/sync/recibe.wsdl
mar 05, 2023 9:00:52 PM com.roshka.sifen.internal.helpers.SoapHelper makeSoapRequest
INFORMACIÓN: Enviando mensaje SOAP
ERROR:  'Las comillas de apertura se deben utilizar para el atributo "classId" asociado a un tipo de elemento "object".'
mar 05, 2023 9:00:52 PM com.sun.xml.internal.messaging.saaj.soap.EnvelopeFactory createEnvelope
GRAVE: SAAJ0511: no se ha podido crear el elemento Envelope desde el origen especificado
mar 05, 2023 9:00:52 PM com.roshka.sifen.internal.request.ReqRecDe processResponse
ADVERTENCIA: El cuerpo del mensaje SOAP es nulo. No se puede obtener el nodo principal.
mar 05, 2023 9:00:52 PM com.roshka.sifen.internal.request.BaseRequest makeRequest
INFORMACIÓN: Petición realizada, se formatea la respuesta
*

Alguna ayuda al respecto ? 

Gracias !!

**Comment by mcespedeso** [comment]
Esta solucionado

**Comment by jvera2644** [comment]
@mcespedeso como lo solucionaste ?

**Comment by igentiletti** [comment]
Tenemos el mismo problema. Cómo lo solucionaron? Gracias!

**Comment by igentiletti** [comment]
Estamos accediendo desde Argentina y cualquiera sea la URL de SOAP o WSDL que intentemos acceder, nos responde con un redirect a una página de logout de BIG-IP con path `/vdesk/hangup.php3`

**Comment by jrugel** [comment]
igentiletti: tienen un certificado válido instalado? el load balancer
autentica la navegación por medio de certificados (el mismo que se usa para
las firmas digitales)
