### ISSUE TITLE
Agregar campo dBasExe a gCamIVA

### ISSUE THREAD

**Issue by imsrnfo** [roshkadev/rshk-jsifenlib#29]
A partir del 21 de Mayo del 2023 se requiere enviar el campo dBasExe.

Adjunto la documentación sobre dicho cambio. 
[NT_E_KUATIA_013_MT_V150.pdf](https://github.com/roshkadev/rshk-jsifenlib/files/11192879/NT_E_KUATIA_013_MT_V150.pdf)

De ser requerido puedo apoyarlos con el cambio.
Saludos!

**Comment by pablo** [comment]
Gracias por la INFO! Si tenés un PULL REQUEST con el cambio, sería ideal. Si no, agregamos.

**Comment by hriveros22** [comment]
tengo el mismo problema, se va a lanzar un nuevo release de la libreria?

**Comment by pablo** [comment]
Sí. Esta semana liberamos una versión nueva con este campo nuevo.

Además de esto, se corrigen varios puntos.

Saludos!

**Comment by carlosulises** [comment]
La versión test ya pide el campo de forma obligatoria, cuando se levanta la nueva versión?

**Comment by pablo** [comment]
Entre mañana y el viernes liberamos una versión con este soporte.

**Comment by pablo** [comment]
Se liberó la versión 0.2.3 con soporte para este campo.
