### ISSUE TITLE
Retorno nulo al consultar RUC

### ISSUE THREAD

**Issue by mendoza95** [roshkadev/rshk-jsifenlib#3]
Estoy intentando realizar una consulta de RUC mediante la función `consultaRUC` de la clase `Sifen` y estoy obteniendo la siguiente respuesta por parte de el servicio web de Sifen

`
{
    "codigoEstado": 200,
    "respuestaBruta": "<html>\n  <head>\n    <meta name=\"robots\" content=\"noindex,nofollow\">\n    <title>BIG-IP logout page</title>\n    <link rel=\"stylesheet\" type=\"text/css\" HREF=\"/public/include/css/apm.css\">\n    <script src=\"/public/include/js/common.js\" language=\"javascript\"></script>\n    <script src=\"/public/include/js/u_plugin.js\" language=\"javascript\"></script>\n\t\n    <script language=\"javascript\">\n      function InsertActivexControl(clsid, params)\n      {\n          var container = document.getElementById(\"logoutActivexContainer\");\n          \n          if (navigator.appName == \"Microsoft Internet Explorer\") {\n              var paramsCode = \"\";\n              for (var item in params) {\n                  paramsCode += \"<param name='\" + item + \"' value='\" + params[item] + \"'>\";\n              }\n              \n              container.innerHTML = \n                  \"<center><object classId=CLSID:\" + clsid + \" border=0 width=1 height=1>\" +\n                  paramsCode + \"</object></center>\";\n          }\n          else {\n              var pluginHost = new UPluginHost(\"\", container);\n              var control = {\"clsid\": clsid, \"width\": 1, \"height\": 1};\n              pluginHost.hostControl(control, params);\n          }\n      }\n\t  \n      function OnLoad()\n      {\n        var isBrowserControl = false;\n        try {\n            isBrowserControl = (\"undefined\" != typeof(window.external))\n                && (\"unknown\" != typeof(window.external))\n                && (\"undefined\" != typeof(window.external.WebLogonNotifyUser))\n                && (\"unknown\" != typeof(window.external.WebLogonNotifyUser));\n        }\n        catch(e) {}\n        if(!isBrowserControl) {\n            document.getElementById(\"newSessionDIV\").style.visibility = \"visible\";\n        }\n\n        try\n        {\n            if (get_cookie(\"F5_PWS\") == \"1\")\n            {\n                document.cookie = \"F5_PWS=0; path=/; expires=Fri, 01-Jan-1970 00:00:01 GMT\";\n                var pwsClassId = \"7E73BE8F-FD87-44EC-8E22-023D5FF960FF\";\n                InsertActivexControl(pwsClassId, {\"command\": \"exit\"} );\n            }\n        }catch (e) {};\n      }\n    </script>\n  </head>\n\n<body onload=\"OnLoad();\">\n<script>\ntry{\n\n    if(window.external && window.external.WebLogonOnAuthFailure) {\n        window.external.WebLogonOnAuthFailure();\n    }\n}catch(e){};\n    try {\n        window.external.OnHostClose();\n    } catch(e) { }\n</script>\n<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\">\n<meta name=\"viewport\" id=\"viewport\" content=\"initial-scale=1.0\" />\n<meta name=\"robots\" context=\"noindex,nofollow\">\n<script language=\"javascript\">\n//orientation toolbox\nfunction setViewport(){\n    document.getElementById(\"viewport\").setAttribute('content', Math.abs(window.orientation) == 90 ? 'width=device-height, initial-scale=1' : 'width=device-width, initial-scale=1.0' );\n}\nsetViewport();\nwindow.onorientationchange = function() {\n    setViewport();\n}\n</script>\n<table id=\"page_header\">\n  <tr >\n    <td id=\"header_leftcell\"><img src='/public/images/my/flogo.png'/></td>\n    <td id=\"header_rightcell\"></td>\n  </tr>\n  <tr>\n     <td></td>\n     <td id=\"maxTimeoutTd\"><span id=\"maxTimeoutTag\" title=\"\"></span></td>\n  </tr>\n</table>\n<noscript>\n<div id=\"noscript_warning_red\">JavaScript no está habilitado. Habilite JavaScript en su navegador o póngase en contacto con su administrador de sistema para obtener ayuda.</div>\n<div id=\"noscript_warning_newsession\">Para abrir una nueva sesión,  <A href=\"/\">haga clic aquí.</A></div>\n</noscript>\n<table id=\"main_table\" class=\"logout_page\">\n<tr>\n        <td id=\"main_table_info_cell\">\n        <table id=\"interaction_table\">\n            <tr>\n                <td id=\"interaction_table_header\">Su sesión ha finalizado.</td>\n            </tr>\n            <tr>\n                <td class=\"interaction_table_option_cell\"><br><DIV ID=\"sessionDIV\" style='visibility:hidden' align=left></DIV>\n                    Cerró la sesión exitosamente.<br>                    <br>Gracias por usar BIG-IP.<br><br>\n                    <div id=\"newSessionDIV\" style='visibility:hidden'>Para abrir una nueva sesión,  <A href='/'>haga clic aquí.</A></div>                </td>\n            </tr>\n            <tr>\n                <td class=\"interaction_table_footer\"></td>\n            </tr>\n        </table>\n    </td>\n    <td id=\"main_table_image_cell\"><img src=\"/public/images/my/tr.gif\"></td></tr>\n</table>\n<div id=\"page_footer\"><div>Este producto tiene la autorización de F5 Networks. © 1999-2018 F5 Networks. Todos los derechos reservados</div></div>\n<DIV ID=\"logoutActivexContainer\" class=\"inspectionHostDIVSmall\"></DIV>\n\n</body>\n</html>\n",
    "dCodRes": null,
    "dMsgRes": null,
    "xContRUC": null
}
`

Ademas en el log generado por la libreria obtengo los siguientes mensajes:

`
2022-03-02 22:13:41.741  INFO 61835 --- [nio-8080-exec-6] class com.roshka.sifen.Sifen             : Preparando petición 'Consulta de RUC'
2022-03-02 22:13:41.775  INFO 61835 --- [nio-8080-exec-6] c.r.sifen.internal.request.BaseRequest   : XML generado, se realiza la petición
2022-03-02 22:13:41.838  INFO 61835 --- [nio-8080-exec-6] c.r.s.internal.helpers.SSLContextHelper  : Contexto SSL no cargado aún. Empezando carga...
2022-03-02 22:13:41.854  INFO 61835 --- [nio-8080-exec-6] c.r.sifen.internal.helpers.SoapHelper    : Conectando a: https://sifen-test.set.gov.py/de/ws/consultas/consulta-ruc.wsdl
2022-03-02 22:13:42.103  INFO 61835 --- [nio-8080-exec-6] c.r.sifen.internal.helpers.SoapHelper    : Enviando mensaje SOAP
ERROR:  'Open quote is expected for attribute "classId" associated with an  element type  "object".'
2022-03-02 22:13:42.306 ERROR 61835 --- [nio-8080-exec-6] c.sun.xml.internal.messaging.saaj.soap   : SAAJ0511: Unable to create envelope from given source
2022-03-02 22:13:42.306  WARN 61835 --- [nio-8080-exec-6] c.r.sifen.internal.request.ReqConsRuc    : El cuerpo del mensaje SOAP es nulo. No se puede obtener el nodo principal.
2022-03-02 22:13:42.307  INFO 61835 --- [nio-8080-exec-6] c.r.sifen.internal.request.BaseRequest   : Petición realizada, se formatea la respuesta
`

Para la configuration de Sifen estableci los siguientes parámetros:

- TipoAmbiente = DEV
- idCSC = 0002
- CSC = EFGH0000000000000000000000000000
- TipoCertificadoCliente = PFX

El certificado de cliente y la constraseña me fueron proveídos por la empresa donde desarrollo. Finalmente, ejecuto las siguientes lineas de código:

`
Sifen.setSifenConfig(config);
RespuestaConsultaRUC consulta = Sifen.consultaRUC(ruc);
`

Me podrían indicar si existe algún error en mi configuración o si necesito algún permiso extra para realizar la consulta a Sifen.

**Comment by martinzarza** [comment]
Normalmente ese error se debe a que el certificado no está correctamente configurado o, en mi experiencia, el ambiente de desarrollo de Sifen no está funcionando por algún motivo. 

Si crees que tu certificado está correcto (podés comentar acá la configuración si tenés dudas) lo que podés hacer es esperar unas horas e intentar de vuelta.

**Comment by martinzarza** [comment]
Sí, mejor utilizar el formato .pfx directamente, aunque sean similares con el .p12. Al parecer con cambiar la extensión basta.

Si con eso seguís teniendo inconvenientes, podés comentar de vuelta y revisamos el inconveniente.

**Comment by mendoza95** [comment]
Hola, justamente ese es el inconveniente que tengo. El formato de mi archivo es .pfx ahora pero al realizar la consulta de ruc me salta el error que se menciona arriba. Los objetos que retornan el servicio web de sinfín retornan con valores nulos: '"dCodRes": null, "dMsgRes": null, "xContRUC": null'.

En el log obtengo este error: 'ERROR:  'Open quote is expected for attribute "classId" associated with an  element type  "object".''

Y luego las siguientes lineas
2022-03-04 13:21:54.949 ERROR 68011 --- [nio-8080-exec-3] c.sun.xml.internal.messaging.saaj.soap   : SAAJ0511: Unable to create envelope from given source
2022-03-04 13:21:54.950  WARN 68011 --- [nio-8080-exec-3] c.r.sifen.internal.request.ReqConsRuc    : El cuerpo del mensaje SOAP es nulo. No se puede obtener el nodo principal.
2022-03-04 13:21:54.950  INFO 68011 --- [nio-8080-exec-3] c.r.sifen.internal.request.BaseRequest   : Petición realizada, se formatea la respuesta

**Comment by mendoza95** [comment]
Hola, ya se cual es el motivo del error anterior. Es un problema del certificado que me pasaron. Ahora me esta saltando otra excepción de la libreria antes de realizar la autenticación a Sifen y quería consultar cual puede ser el motivo. La excepción que me salta seria la siguiente:
`c.r.s.internal.helpers.SSLContextHelper  : El certificado no es un archivo. Intentando decodificar...
com.roshka.sifen.core.exceptions.SifenException: No se puede cargar el certificado de cliente: Illegal base64 character 5f] with root cause
java.lang.IllegalArgumentException: Illegal base64 character 5f`

Me podrían indicar cuál es el motivo de la excepción.

**Comment by martinzarza** [comment]
En qué formato estás usando el certificado? Se puede hacer de dos formas: usando la ruta absoluta de donde está almacenado, o convertir el certificado a un string en Base64.

**Comment by mendoza95** [comment]
Hola, estoy utilizando la ruta absoluta de certificado. Podría ser ese el problema?

**Comment by martinzarza** [comment]
No, esa es una de las formas, así que está bien. Pero por lo que veo en el mensaje de error no está pudiendo leer tu archivo. Podrías mostrar como está tu configuración de Sifen? La contraseña podés reemplazar nomás por otro valor por razones de seguridad.
