### ISSUE TITLE
Ignorancia mia.. 

### ISSUE THREAD

**Issue by picolo01** [roshkadev/rshk-jsifenlib#34]
Disculpen por la pregunta torpe.. pero en cuanto tiempo estaría disponible en Maven central la ultima versión? 
Por que al colocar en el pom.xml
<dependency>
            <groupId>com.roshka.sifen</groupId>
            <artifactId>rshk-jsifenlib</artifactId>
            <version>0.2.3</version>
        </dependency>
me tira error?
en serio no pillo como se actualiza

**Comment by trinidadmarcelo** [comment]
ahora veo que ya aparece en Maven

**Comment by picolo01** [comment]
en que repositorio? https://search.maven.org/search?q=com.roshka.sifen aqui solo me tira la version anterior

**Comment by pablo** [comment]
Tarda en sincronizar en todos los servidores. A mi ya me aparece en casi todos menos en https://mvnrepository.com/artifact/com.roshka.sifen/rshk-jsifenlib

Cierro por ahora el ISSUE.
