### ISSUE TITLE
CDC menos a 8 caracteres

### ISSUE THREAD

**Issue by picolo01** [roshkadev/rshk-jsifenlib#37]
CDC = SifenUtil.leftPad(String.valueOf(this.getgTimb().getiTiDE().getVal()), '0', 2) +
                    this.getgDatGralOpe().getgEmis().getdRucEm() +
                    this.getgDatGralOpe().getgEmis().getdDVEmi() +
                    this.getgTimb().getdEst() +
                    this.getgTimb().getdPunExp() +
                    this.getgTimb().getdNumDoc() +
                    this.getgDatGralOpe().getgEmis().getiTipCont().getVal() +
                    this.getgDatGralOpe().getdFeEmiDE().format(formatter) +
                    this.getgOpeDE().getiTipEmi().getVal() +
                    this.getgOpeDE().getdCodSeg();
Cuando el ruc es menos de 8 caracteres calcula con 42/43 caracteres el CDC

**Comment by picolo01** [comment]
CDC = SifenUtil.leftPad(String.valueOf(this.getgTimb().getiTiDE().getVal()), '0', 2) +
                    SifenUtil.leftPad(String.valueOf( this.getgDatGralOpe().getgEmis().getdRucEm()), '0', 8) +
                    this.getgDatGralOpe().getgEmis().getdDVEmi() +
                    this.getgTimb().getdEst() +
                    this.getgTimb().getdPunExp() +
                    this.getgTimb().getdNumDoc() +
                    this.getgDatGralOpe().getgEmis().getiTipCont().getVal() +
                    this.getgDatGralOpe().getdFeEmiDE().format(formatter) +
                    this.getgOpeDE().getiTipEmi().getVal() +
                    this.getgOpeDE().getdCodSeg();

Podrian cambiar esta parte para su siguiente version?

**Comment by pablo** [comment]
Claro. Agregamos sin problemas.
