### ISSUE TITLE
Problema en generación de firma digital

### ISSUE THREAD

**Issue by mendoza95** [roshkadev/rshk-jsifenlib#4]
Buenas tardes,

Estoy teniendo un problema en la generación de la firma digital. Puedo usar correctamente mi certificado pero la firma generada tiene problemas. La gente de Sifen me indico que los carctares `&#13;` al final de cada linea en los campos `SignatureValue` y `X509Certificate` producen errores al tratar de validar la firma en del lado de Sifen. Es posible que la generación de esos carácteres al generar la firma con la libreria se deba a una mala configuración del certificado? La configuración que utilizo es la siguiente:

`SifenConfig config = new SifenConfig(`
`                SifenConfig.TipoAmbiente.DEV,`
                `"0002", // ID CSC`
                `"EFGH0000000000000000000000000000", // CSC`
`                SifenConfig.TipoCertificadoCliente.PFX,`
  `              "/Users/fabriciomendozagranada/Documents/CDS/sifenbridge/certificado_digital.pfx",`
`                "password"`
        );
      `  config.setUsarCertificadoCliente(true);`

`        Sifen.setSifenConfig(config);`

**Comment by rafaelviny** [comment]
Buenas tardes, estoy teniendo el mismo problema. como se resolvio?
