### ISSUE TITLE
Libreria

### ISSUE THREAD

**Issue by Luisxxxortiz** [roshkadev/rshk-jsifenlib#5]
Buenos dias como estan... tengo un problema con la libreria uso netbeans para abrir el proyecto pero no me reconoce el import java.xml.soap...

**Comment by martinzarza** [comment]
Qué versión de Java estás usando? Para la librería se necesita el 8.

**Comment by Luisxxxortiz** [comment]
actualmente estaba usando la version 8 lo cual me daba el mismo problema luego instale la version 7 
pero igual

**Comment by Luisxxxortiz** [comment]
la verdad soy programador de c# pero me cuesta todavia implementar un sistema asi... ya he echo un sistema de ventas... entiendo tambien de java solo tengo ese problema con el import

**Comment by martinzarza** [comment]
Podes enviar una captura de pantalla del error, y de la versión de Java que estás usando?

El paquete java.xml.soap es nativo de Java, así que no debería ser otra cosa más que la versión de Java.

**Comment by Luisxxxortiz** [comment]
![Screenshot 2022-04-16 11-08-21](https://user-images.githubusercontent.com/79720318/163680215-c4e038c9-1c65-42a8-8e7b-348419875353.png)
![Screenshot 2022-04-16 11-09-07](https://user-images.githubusercontent.com/79720318/163680222-f1f05a8c-a59d-4bd0-9ddf-2d3d2b731a5c.png)

**Comment by Luisxxxortiz** [comment]
version java 8 y me marca el error en javax.xml.soap

**Comment by Luisxxxortiz** [comment]
solucione el problema cambiando la dependencia de jdk18 a jdk 1.8... gracias por la atencion que tenga excelente dia

**Comment by Luisxxxortiz** [comment]
Disculpe una ultima pregunta si me podrian orientar un poco por favor
... ¿Para hacer las pruebas tengo que tener el certificado pxf? 
¿Donde puedo conseguir ese certificado?

**Comment by crontabpy** [comment]
Buenas que tal... que posibilidad hay de que se incluya un ejemplo de codigo para enviar una factura con los datos de cabecera y detalle?
Algo parecido al ejempo de consulta de ruc que se puso. 
Saludos

**Comment by crontabpy** [comment]
> Disculpe una ultima pregunta si me podrian orientar un poco por favor ... ¿Para hacer las pruebas tengo que tener el certificado pxf? ¿Donde puedo conseguir ese certificado?

Si tenes que tener el certificado, inclusive para el ambiente de test. Podes conseguir con las empresas habilitadas para tal fin. Efirma se llama una de ellas.

**Comment by martinzarza** [comment]
@Luisxxxortiz Sí, necesitas conseguir el certificado para utilizar el ambiente de test. Actualmente no sé si para utilizar Sifen se debe solicitar a la SET o es libre, eso lo podés averiguar con ellos.

**Comment by luisdgd07** [comment]
Como lograste solucionar el problema con el import?

**Comment by Luisxxxortiz** [comment]
Muchas Gracias por las respuestas
