### ISSUE TITLE
Problemas con firma digital &#13; al final de cada linea

### ISSUE THREAD

**Issue by ArielTalavera** [roshkadev/rshk-jsifenlib#52]
Buenas tardes,

Estoy teniendo un problema en la generación de la firma digital. Puedo usar correctamente mi certificado pero la firma generada tiene problemas. La gente de Sifen me indico que los carctares &#13; al final de cada linea en los campos SignatureValue y X509Certificate producen errores al tratar de validar la firma en del lado de Sifen. Es posible que la generación de esos carácteres al generar la firma con la libreria se deba a una mala configuración del certificado? La configuración que utilizo es la siguiente:

SifenConfig config = new SifenConfig(
                SifenConfig.TipoAmbiente.DEV,
"0002", // ID CSC
"EFGH0000000000000000000000000000", // CSC
                SifenConfig.TipoCertificadoCliente.PFX,
              "/Users/fabriciomendozagranada/Documents/CDS/sifenbridge/certificado_digital.pfx",
                "password"
);
  config.setUsarCertificadoCliente(true);

        Sifen.setSifenConfig(config);

**Comment by ArielTalavera** [comment]
![image](https://github.com/roshkadev/rshk-jsifenlib/assets/6431348/fcf9c20b-a639-4dd7-bd51-fe9c975495c6)


este seria el caracter que me agrega, pero lo raro es que no sucede en todos los casos

**Comment by pablo** [comment]
En algunos casos funciona y en otros hay error de firma? Podés pasar un ejemplo que sí funciona y un ejemplo que no? Voy a ver si se repite con nuestro certificado.

**Comment by ArielTalavera** [comment]
[factyras.zip](https://github.com/roshkadev/rshk-jsifenlib/files/12306814/factyras.zip)

en el tenes 2 archivos ya firmados.

01800026799008003000441922023080911676648437 este cdc es el que me aprobo la set

01800026799002002000136922023080714904228630 este me recahza la set y tiene el enter en la firma en cada linea.. no se por que le agrega

**Comment by ArielTalavera** [comment]
desde ya muchas gracias por tu respuesta

**Comment by CRkloontech** [comment]
Buen día. Solo para reportar que estamos con el mismo problema, al intentar auténticar el DE en la sifen algunas vezes nos retorna el error de xlm mal formatado por el tema del &#13 en la firma. El XML es generado de igual forma todas las vezes pero en algunos casos en el momento de la firma nos agrega esse carácter.

**Comment by ArielTalavera** [comment]
Yo solucione de forma provisoria.. tuve que descargar los codigos fuentes.. agregar a mi proyecto y modificar la clase ReqRecLoteDe.java 

![image](https://github.com/roshkadev/rshk-jsifenlib/assets/6431348/e71a71df-e7df-427d-b0c3-069872fbc86f)


luego de ahi si ya puedo enviar.

Otro dato curioso, yo genero y envio desde mi pc de desarrollo y sin problema... llevo al servidor en produccion y ahi tengo el problema..  no se si tiene algo que ver...

**Comment by pablo** [comment]
Buenísimo Ariel. Vamos a investigar en profundidad, y analizar la inclusión de esa línea para todos.
