### ISSUE TITLE
validacion de firma digital del DE recibido

### ISSUE THREAD

**Issue by crontabpy** [roshkadev/rshk-jsifenlib#7]
Buenas.
Hay algun metodo en la libreria que se pueda utilizar para validar que la firma digital de un DE (Documento Electronico) recibido por parte de un emisor correspondan al contenido del DE?

Si bien SIFEN realiza estas validaciones cuando se envia un DE al web service,  entiendo que existe la posibilidad de que, por ejemplo, un proveedor envie una factura electronica a su cliente sin haber pasado por el SIFEN todavia.

**Comment by martinzarza** [comment]
Actualmente la librería no cuenta con esa funcionalidad, pero me parece interesante. No sé si es posible realizar esto sin tener algún tipo de información acerca del certificado del emisor, pero lo vamos a investigar.

Le agrego la etiqueta de **mejora** a este _issue_ para darle seguimiento.

**Comment by martinzarza** [comment]
@crontabpy Ya está disponible la validación de la firma digital de un Documento Electrónico en particular en la nueva versión 0.2.0. En unas horas será posible descargar desde el repositorio de Maven.

Se valida que la firma sea la correcta, y también que el RUC del dueño del certificado utilizado para la firma coincida con el emisor del documento.

Estos son los tres nuevos métodos:

```java
// Ruta del archivo
Sifen.validarFirmaDE("/path/to/xml");

// Objeto File
Sifen.validarFirmaDE(new File("/path/to/xml"));

// String del xml
Sifen.validarFirmaDEDesdeXml("<?xml>");
```
