### ISSUE TITLE
certificados ya no seran entregados en medio fisico?

### ISSUE THREAD

**Issue by crontabpy** [roshkadev/rshk-jsifenlib#8]
Buenas. Que hay de cierto de que el MIC esta cambiando la reglamentación en cuanto a emision de certificados?

Segun me comentaron que los certificados de firma digital ya no se van a entregar por medios fisicos y que estos unicamente van a ser accedidos por una API con usuario y contraseña.

**Comment by martinzarza** [comment]
Nosotros no manejamos este tipo de información. Deberías consultar al MIC o incluso a la SET para aclarar tus dudas.
